[project]
name = "tsio"
version = "0.1.0"
description = "A Python Command Line Interface (CLI) application to handle various file formats"
authors = [
    {name = "Christopher Field", email = "chris.field@theiascientific.com"},
]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [ "Programming Language :: Python :: 3", "Operating System :: OS Independent" ]
dependencies = [
    "numpy",
    "opencv-contrib-python-headless",
    "opencv-python-headless",
    "pydantic",
    "pydantic-settings",
    "rosettasciio[all]",
    "tdqm",
    "typer",
]

[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"

[project.optional-dependencies]
dev = [ "build", "flake8", "hatch", "isort", "pytest", "pytest-cov", "pytest-env", "twine" ]

[project.scripts]
tsio = "tsio.cli:app"

[project.urls]
Homepage = "https://github.com/Theia-Scientific/tsio"
"Bug Tracker" = "https://github.com/Theia-Scientific/tsio/issues"

[tool.coverage.report]
exclude_lines = [ "if __name__ == .__main__.:" ]
omit = [ "__main__.py" ]
